services:
  postgres:
    image: postgres:18
    container_name: housing_postgres
    environment:
      POSTGRES_USER: housing
      POSTGRES_PASSWORD: housing
      POSTGRES_DB: housing
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:7
    container_name: housing_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
